# Generated by Django 4.2.9 on 2024-02-08 08:21

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='data',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('link', models.CharField(max_length=1000)),
                ('inputtext', models.CharField(max_length=1000)),
                ('option', models.CharField(max_length=1000)),
            ],
        ),
    ]
